deploy backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,6 +20,7 @@ commands:
             fi
             aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow_id>>
             aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow_id>>
+
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
@@ -39,6 +40,7 @@ commands:
               npm install
               npm run migration:revert
             fi
+
 jobs:
   build-frontend:
     docker:
@@ -274,7 +276,7 @@ jobs:
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
-	run-migrations:
+  run-migrations:
     docker:
       - image: sleavely/node-awscli:14.x
     steps:
@@ -287,7 +289,7 @@ jobs:
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
-     - run:
+      - run:
           name: Run migrations
           command: |
             cd backend
@@ -322,7 +324,7 @@ jobs:
       - checkout
       - restore_cache:
           keys: [frontend-build]
-       - run:
+      - run:
           name: Install dependencies
           command: |
             sudo apt update
@@ -358,84 +360,89 @@ jobs:
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
-  deploy-backend:	
-    docker:	
-      - image: python:3.9.1-alpine3.12     	
-    steps:	
-      - checkout	
-      - add_ssh_keys:	
-          fingerprints: ["14:45:30:21:c6:8d:8d:5f:ab:b8:24:3c:43:c2:70:90"]	
-      - attach_workspace: 	
-          at: ~/	
-      - restore_cache:	
-          keys: [backend-build]	
-      - run:	
-          name: Install dependencies	
-          command: |	
-            apk add --update curl nodejs npm	
-            apk add --update ansible zip	
-            apk add --update openssh-client tar gzip	
-            pip install awscli	
-      - run:	
-          name: Package backend	
-          command: |	
-            cd backend	
-            npm install typescript@latest -g	
-            npm install	
-            npm run build	
-            tar -czf artifact.tar.gz dist/* package*	
-            cd ..	
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files	
-      - run:	
-          name: Deploy backend	
-          command: |	
-            export TYPEORM_MIGRATIONS_DIR=./migrations	
-            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}	
-            export TYPEORM_MIGRATIONS=./migrations/*.ts	
-            	
-            cd .circleci/ansible	
-            cat inventory.txt	
-            export ANSIBLE_HOST_KEY_CHECKING=False	
-            ansible-playbook -i inventory.txt deploy-backend.yml	
-      - slack/notify:	
-          event: pass	
-          template: success_tagged_deploy_1	
-      - slack/notify:	
-          event: fail	
-          template: basic_fail_1	
-      # Here's where you will add some code to rollback on failure	
-      - destroy-environment:	
+  deploy-backend:
+    docker:
+      - image: python:3.9.1-alpine3.12     
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints: ["14:45:30:21:c6:8d:8d:5f:ab:b8:24:3c:43:c2:70:90"]
+      - attach_workspace: 
+          at: ~/
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl nodejs npm
+            apk add --update ansible zip
+            apk add --update openssh-client tar gzip
+            pip install awscli
+      - run:
+          name: Package backend
+          command: |
+            cd backend
+            npm install typescript@latest -g
+            npm install
+            npm run build
+            tar -czf artifact.tar.gz dist/* package*
+            cd ..
+            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+      - run:
+          name: Deploy backend
+          command: |
+            export TYPEORM_MIGRATIONS_DIR=./migrations
+            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+            export TYPEORM_MIGRATIONS=./migrations/*.ts
+            
+            cd .circleci/ansible
+            cat inventory.txt
+            export ANSIBLE_HOST_KEY_CHECKING=False
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      - slack/notify:
+          event: pass
+          template: success_tagged_deploy_1
+      - slack/notify:
+          event: fail
+          template: basic_fail_1
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   smoke-test:
     docker:
       - image: python:3.9.1-alpine3.12
     steps:
+      # Checkout code from git
       - checkout
       - run:
           name: Install dependencies
           command: |
             apk add --update curl
             pip install awscli
-      - run:	
-          name: Backend smoke test.	
-          command: |	
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \	
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \	
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \	
-              --output text)	
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030	
-            echo ${API_URL}	
-            if curl -s $API_URL/api/status | grep "ok"	
-            then	
-              exit 0	
-            else	
-              exit 1	
+      - run:
+          name: Backend smoke test.
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text)
+
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+
+            echo ${API_URL}
+
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
             fi
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com"             	            echo ${URL} 
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com"             
+            echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
               exit 0
@@ -449,10 +456,10 @@ jobs:
           event: fail
           template: basic_fail_1
       # Here's where you will add some code to rollback on failure
-      # - destroy-environment:
-          # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      # - revert-migrations:
-          # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      #- destroy-environment:
+          #workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      #- revert-migrations:
+          #workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
 workflows:
   default:
